### PR TITLE
Fix: Relax S1 regex to avoid false positive

### LINKED ISSUE #62: single-space-decorator: False positive for curly brackets in strings
Required code for python format function:
````jinja
{% set row.line = row.line ~ "| {t:{t_width}} ".format(t=text, t_width=table.column_width[key]) %}
````
fails with message:
````code
template.j2:58 A single space shall be added between Jinja2 curly brackets and a variable name: {{ ethernet_interface }} (single-space-decorator)
````

### PR DESCRIPTION
**Pull request by gmuloc**
Fixes #62

### CODE REVIEW

**Comment by kornoa** [comment]
Is there a reason why there is no release?

**Comment by carlbuchmann** [comment]
> Is there a reason why there is no release?

@kornoa, Thank you for your patience. The maintainer team has been busy with the AVD 4.0 release. @gmuloc and I will work on a new release promptly!

**Review by carlbuchmann — APPROVED** [review]
LGTM

**Comment by kornoa** [comment]
Excellent! I've already noticed the release of v1.1.0. Many thanks!

**Pull request merged**
